const sex = "I AM UNABLE TO HAVE SEX ANYMORE
BECAUSE I CUMMED SO MUCH TODAY,
THAT I DO NOT HAVE ANY MORE CUM
LEFT TO SHOOT OUT. HERE'S A LIST OF
THINGS THAT I FUCKED ALL MY MIGHT
ON: NEIGHBOR'SDOG CAT ELEPHANT LION
TIGER GIRAFFE BEAR KANGAROO
PENGUIN DOLPHIN OWL HORSE MONKEY
GORILLA CROCODILE SNAKE ZEBRA
RHINO (RHINOCEROS) CHEETAH WOLF
FOX KOALA SQUIRREL PENGUIN RABBIT I
ALSO SUCKED 287 COCKS AND 11M NOT
ALLERGIC TO CUM BECAUSE I SUCKED
WAY TOO MUCH, THAT MY BODY CAN NO
LONGER DIGEST CUM SO I CANNOT EAT
DICKS ANYMORE. I ALSO FUCKED 87
GIRLS AND 459 MEN. THIS IS WHY I AM NO
LONGER ABLE TO PRODUCE CUM. SINCE I
CANNOT CUM ANYMORE, I SPENT MY
TIME TWISTING PEOPLE VAGINES IN SIDE
OUTI AM UNABLE TO HAVE SEX ANYMORE
BECAUSE I CUMMED SO MUCH TODAY,
THAT I DO NOT HAVE ANY MORE CUM
LEFT TO SHOOT OUT. HERE'S A LIST OF
THINGS THAT I FUCKED ALL MY MIGHT
ON: NEIGHBOR'SDOG CAT ELEPHANT LION
TIGER GIRAFFE BEAR KANGAROO
PENGUIN DOLPHIN OWL HORSE MONKEY
GORILLA CROCODILE SNAKE ZEBRA
RHINO (RHINOCEROS) CHEETAH WOLF
FOX KOALA SQUIRREL PENGUIN RABBIT I
ALSO SUCKED 287 COCKS AND 11M NOT
ALLERGIC TO CUM BECAUSE I SUCKED
WAY TOO MUCH, THAT MY BODY CAN NO
LONGER DIGEST CUM SO I CANNOT EAT
DICKS ANYMORE. I ALSO FUCKED 87
GIRLS AND 459 MEN. THIS IS WHY I AM NO
LONGER ABLE TO PRODUCE CUM. SINCE I
CANNOT CUM ANYMORE, I SPENT MY
TIME TWISTING PEOPLE VAGINES IN SIDE
OUTI AM UNABLE TO HAVE SEX ANYMORE
BECAUSE I CUMMED SO MUCH TODAY,
THAT I DO NOT HAVE ANY MORE CUM
LEFT TO SHOOT OUT. HERE'S A LIST OF
THINGS THAT I FUCKED ALL MY MIGHT
ON: NEIGHBOR'SDOG CAT ELEPHANT LION
TIGER GIRAFFE BEAR KANGAROO
PENGUIN DOLPHIN OWL HORSE MONKEY
GORILLA CROCODILE SNAKE ZEBRA
RHINO (RHINOCEROS) CHEETAH WOLF
FOX KOALA SQUIRREL PENGUIN RABBIT I
ALSO SUCKED 287 COCKS AND 11M NOT
ALLERGIC TO CUM BECAUSE I SUCKED
WAY TOO MUCH, THAT MY BODY CAN NO
LONGER DIGEST CUM SO I CANNOT EAT
DICKS ANYMORE. I ALSO FUCKED 87
GIRLS AND 459 MEN. THIS IS WHY I AM NO
LONGER ABLE TO PRODUCE CUM. SINCE I
CANNOT CUM ANYMORE, I SPENT MY
TIME TWISTING PEOPLE VAGINES IN SIDE
OUTI AM UNABLE TO HAVE SEX ANYMORE
BECAUSE I CUMMED SO MUCH TODAY,
THAT I DO NOT HAVE ANY MORE CUM
LEFT TO SHOOT OUT. HERE'S A LIST OF
THINGS THAT I FUCKED ALL MY MIGHT
ON: NEIGHBOR'SDOG CAT ELEPHANT LION
TIGER GIRAFFE BEAR KANGAROO
PENGUIN DOLPHIN OWL HORSE MONKEY
GORILLA CROCODILE SNAKE ZEBRA
RHINO (RHINOCEROS) CHEETAH WOLF
FOX KOALA SQUIRREL PENGUIN RABBIT I
ALSO SUCKED 287 COCKS AND 11M NOT
ALLERGIC TO CUM BECAUSE I SUCKED
WAY TOO MUCH, THAT MY BODY CAN NO
LONGER DIGEST CUM SO I CANNOT EAT
DICKS ANYMORE. I ALSO FUCKED 87
GIRLS AND 459 MEN. THIS IS WHY I AM NO
LONGER ABLE TO PRODUCE CUM. SINCE I
CANNOT CUM ANYMORE, I SPENT MY
TIME TWISTING PEOPLE VAGINES IN SIDE
OUT"
